"""
Database layer: PostgreSQL (optional) or local SQLite fallback.

This file is the "persistence engine" for the bot.

We support two storage backends:
  1) PostgreSQL (recommended for production)
     - enabled when you set DATABASE_URL in environment (.env)
  2) SQLite (default for local development)
     - used automatically when DATABASE_URL is not set
     - stored as a local file: `seashell.db` in the project folder

Important rule:
  - user_id everywhere == Telegram chat_id (int).

Tables we manage:
  - vocabulary:
      one row per user word (word + meaning/translation)
  - vocabulary_examples:
      cached example sentences per word (generated by AI in batches to save tokens)
  - user_settings:
      user preferences (native language for translations)

Call `init_db()` once at startup to create missing tables.

FAQ:
  Q: I see "DATABASE_URL is not set" in logs. Is it an error?
  A: No. It means we will use local SQLite file `seashell.db` automatically.

  Q: Where is the SQLite database file?
  A: Next to this file (`db.py`) inside the project folder: `seashell.db`.

  Q: Can I move from SQLite to PostgreSQL later?
  A: Yes, but you will need a migration (export/import data). Right now this file does not
     auto-migrate; it just chooses backend based on DATABASE_URL.

  Q: Why do you have both `?` and `%s` in SQL?
  A: SQLite uses `?` placeholders; PostgreSQL (psycopg2) uses `%s`.

  Q: I deleted a word. Will its cached examples be deleted too?
  A: Yes. `vocabulary_examples.word_id` has `ON DELETE CASCADE`.
"""

import os
import logging
from contextlib import contextmanager
import uuid
from pathlib import Path
import json

logger = logging.getLogger(__name__)


def get_database_url():
    """
    Read DATABASE_URL from environment.

    If it is missing, we will use SQLite fallback automatically.
    """
    url = os.getenv("DATABASE_URL")
    if not url:
        logger.warning("DATABASE_URL is not set; using local SQLite fallback.")
    return url


@contextmanager
def get_connection():
    """
    Context manager that yields a DB connection.
    - If DATABASE_URL is set: uses PostgreSQL.
    - Otherwise: uses local SQLite file `seashell.db`.
    """
    url = get_database_url()
    if url:
        # PostgreSQL path (psycopg2).
        try:
            import psycopg2
            conn = psycopg2.connect(url)
            conn.autocommit = False
            try:
                yield conn
                conn.commit()
            except Exception:
                conn.rollback()
                raise
            finally:
                conn.close()
        except Exception as e:
            logger.exception("PostgreSQL connection error: %s", e)
            raise
        return

    # SQLite fallback
    import sqlite3

    project_root = Path(__file__).resolve().parent
    db_path = project_root / "seashell.db"
    # sqlite3 connects to a file. If file doesn't exist, it will be created.
    conn = sqlite3.connect(db_path)
    try:
        # Enforce foreign keys in SQLite (off by default).
        conn.execute("PRAGMA foreign_keys = ON;")
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db():
    """
    Create vocabulary table if it does not exist.
    Safe to call on every startup (IF NOT EXISTS).
    """
    with get_connection() as conn:
        if conn is None:
            return
        is_sqlite = conn.__class__.__module__.startswith("sqlite3")
        if is_sqlite:
            # SQLite schema.
            cur = conn.cursor()
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vocabulary (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    word TEXT NOT NULL,
                    meaning TEXT,
                    created_at TEXT DEFAULT (datetime('now'))
                )
                """
            )
            cur.execute("CREATE INDEX IF NOT EXISTS idx_vocabulary_user_id ON vocabulary (user_id)")
            cur.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS uniq_vocabulary_user_word ON vocabulary (user_id, lower(word))"
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vocabulary_examples (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    word_id INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,
                    batch_id TEXT NOT NULL,
                    example_text TEXT NOT NULL,
                    served INTEGER NOT NULL DEFAULT 0,
                    created_at TEXT DEFAULT (datetime('now'))
                )
                """
            )
            cur.execute(
                "CREATE INDEX IF NOT EXISTS idx_vocab_examples_user_word_served ON vocabulary_examples (user_id, word_id, served, created_at)"
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS user_settings (
                    user_id INTEGER PRIMARY KEY,
                    native_language TEXT NOT NULL DEFAULT 'ru'
                )
                """
            )
            # --- Product/UX state ---
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS user_profiles (
                    user_id INTEGER PRIMARY KEY,
                    onboarding_done INTEGER NOT NULL DEFAULT 0,
                    created_at TEXT DEFAULT (datetime('now'))
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS speaking_sessions (
                    user_id INTEGER PRIMARY KEY,
                    speed TEXT NOT NULL DEFAULT 'normal',
                    history_json TEXT NOT NULL,
                    updated_at TEXT DEFAULT (datetime('now'))
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS usage_stats (
                    user_id INTEGER PRIMARY KEY,
                    words_added INTEGER NOT NULL DEFAULT 0,
                    examples_generated INTEGER NOT NULL DEFAULT 0,
                    examples_served INTEGER NOT NULL DEFAULT 0,
                    speaking_turns INTEGER NOT NULL DEFAULT 0,
                    speaking_recaps INTEGER NOT NULL DEFAULT 0,
                    updated_at TEXT DEFAULT (datetime('now'))
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS vocab_active_session (
                    user_id INTEGER PRIMARY KEY,
                    word_id INTEGER,
                    updated_at TEXT DEFAULT (datetime('now'))
                )
                """
            )
        else:
            # PostgreSQL schema.
            with conn.cursor() as cur:
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS vocabulary (
                        id SERIAL PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        word TEXT NOT NULL,
                        meaning TEXT,
                        created_at TIMESTAMPTZ DEFAULT NOW()
                    );
                    CREATE INDEX IF NOT EXISTS idx_vocabulary_user_id ON vocabulary (user_id);
                """)
                cur.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS uniq_vocabulary_user_word
                      ON vocabulary (user_id, lower(word));
                """)
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS vocabulary_examples (
                        id SERIAL PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        word_id INT NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,
                        batch_id UUID NOT NULL,
                        example_text TEXT NOT NULL,
                        served BOOLEAN NOT NULL DEFAULT FALSE,
                        created_at TIMESTAMPTZ DEFAULT NOW()
                    );
                    CREATE INDEX IF NOT EXISTS idx_vocab_examples_user_word_served
                      ON vocabulary_examples (user_id, word_id, served, created_at);
                """)
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS user_settings (
                        user_id BIGINT PRIMARY KEY,
                        native_language TEXT NOT NULL DEFAULT 'ru'
                    );
                """)
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS user_profiles (
                        user_id BIGINT PRIMARY KEY,
                        onboarding_done INTEGER NOT NULL DEFAULT 0,
                        created_at TIMESTAMPTZ DEFAULT NOW()
                    );
                """)
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS speaking_sessions (
                        user_id BIGINT PRIMARY KEY,
                        speed TEXT NOT NULL DEFAULT 'normal',
                        history_json TEXT NOT NULL,
                        updated_at TIMESTAMPTZ DEFAULT NOW()
                    );
                """)
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS usage_stats (
                        user_id BIGINT PRIMARY KEY,
                        words_added INTEGER NOT NULL DEFAULT 0,
                        examples_generated INTEGER NOT NULL DEFAULT 0,
                        examples_served INTEGER NOT NULL DEFAULT 0,
                        speaking_turns INTEGER NOT NULL DEFAULT 0,
                        speaking_recaps INTEGER NOT NULL DEFAULT 0,
                        updated_at TIMESTAMPTZ DEFAULT NOW()
                    );
                """)
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS vocab_active_session (
                        user_id BIGINT PRIMARY KEY,
                        word_id INT,
                        updated_at TIMESTAMPTZ DEFAULT NOW()
                    );
                """)
        logger.info("Database schema checked (vocabulary table).")


def get_native_language(user_id: int) -> str:
    """
    Get user's native language code (e.g. 'ru', 'es').

    If the user never opened settings, we return default: 'ru'.
    """
    try:
        with get_connection() as conn:
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute("SELECT native_language FROM user_settings WHERE user_id = ?", (user_id,))
                row = cur.fetchone()
                return row[0] if row and row[0] else "ru"
            else:
                with conn.cursor() as cur:
                    cur.execute("SELECT native_language FROM user_settings WHERE user_id = %s", (user_id,))
                    row = cur.fetchone()
                    return row[0] if row and row[0] else "ru"
    except Exception as e:
        logger.exception("get_native_language failed: %s", e)
        return "ru"


def set_native_language(user_id: int, lang: str) -> bool:
    """
    Save user's native language (upsert).

    We keep it short and store only a language code string.
    """
    lang = (lang or "").strip().lower() or "ru"
    try:
        with get_connection() as conn:
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute(
                    """
                    INSERT INTO user_settings (user_id, native_language)
                    VALUES (?, ?)
                    ON CONFLICT(user_id) DO UPDATE SET native_language=excluded.native_language
                    """,
                    (user_id, lang),
                )
                return cur.rowcount > 0
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO user_settings (user_id, native_language)
                        VALUES (%s, %s)
                        ON CONFLICT (user_id) DO UPDATE SET native_language = EXCLUDED.native_language
                        """,
                        (user_id, lang),
                    )
                    return cur.rowcount > 0
    except Exception as e:
        logger.exception("set_native_language failed: %s", e)
        return False


# ---------------------------------------------------------------------------
# Vocabulary API (used by vocabulary module)
# ---------------------------------------------------------------------------


def add_word(user_id: int, word: str, meaning: str = None) -> bool:
    """
    Add a word for the user. user_id is Telegram chat_id.
    Returns True if inserted, False on error or duplicate (same user_id + word).
    """
    if not word or not word.strip():
        return False
    # Normalize input a bit.
    word = word.strip()
    meaning = (meaning or "").strip() or None
    try:
        with get_connection() as conn:
            if conn is None:
                return False
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                # INSERT OR IGNORE prevents duplicates (unique index on user_id + lower(word)).
                cur = conn.cursor()
                cur.execute(
                    """
                    INSERT OR IGNORE INTO vocabulary (user_id, word, meaning)
                    VALUES (?, ?, ?)
                    """,
                    (user_id, word, meaning),
                )
                return cur.rowcount > 0
            else:
                # PostgreSQL: ON CONFLICT prevents duplicates.
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO vocabulary (user_id, word, meaning)
                        VALUES (%s, %s, %s)
                        ON CONFLICT (user_id, lower(word)) DO NOTHING
                        """,
                        (user_id, word, meaning),
                    )
                    return cur.rowcount > 0
    except Exception as e:
        logger.exception("add_word failed: %s", e)
        return False


def get_words(user_id: int, limit: int = 100, offset: int = 0):
    """
    Return list of (id, word, meaning, created_at) for the user, newest first.
    """
    try:
        with get_connection() as conn:
            if conn is None:
                return []
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                # SQLite uses ? placeholders.
                cur = conn.cursor()
                cur.execute(
                    """
                    SELECT id, word, meaning, created_at
                    FROM vocabulary
                    WHERE user_id = ?
                    ORDER BY created_at DESC
                    LIMIT ?
                    OFFSET ?
                    """,
                    (user_id, limit, offset),
                )
                return cur.fetchall()
            else:
                # PostgreSQL uses %s placeholders.
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        SELECT id, word, meaning, created_at
                        FROM vocabulary
                        WHERE user_id = %s
                        ORDER BY created_at DESC
                        LIMIT %s
                        OFFSET %s
                        """,
                        (user_id, limit, offset),
                    )
                    return cur.fetchall()
    except Exception as e:
        logger.exception("get_words failed: %s", e)
        return []


def get_word(user_id: int, word_id: int):
    """Return (id, word, meaning, created_at) for the user or None."""
    try:
        with get_connection() as conn:
            if conn is None:
                return None
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute(
                    """
                    SELECT id, word, meaning, created_at
                    FROM vocabulary
                    WHERE user_id = ? AND id = ?
                    """,
                    (user_id, word_id),
                )
                return cur.fetchone()
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        SELECT id, word, meaning, created_at
                        FROM vocabulary
                        WHERE user_id = %s AND id = %s
                        """,
                        (user_id, word_id),
                    )
                    return cur.fetchone()
    except Exception as e:
        logger.exception("get_word failed: %s", e)
        return None


def delete_word(user_id: int, word_id: int) -> bool:
    """Delete a vocabulary entry by id if it belongs to the user."""
    try:
        with get_connection() as conn:
            if conn is None:
                return False
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute(
                    "DELETE FROM vocabulary WHERE id = ? AND user_id = ?",
                    (word_id, user_id),
                )
                return cur.rowcount > 0
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        "DELETE FROM vocabulary WHERE id = %s AND user_id = %s",
                        (word_id, user_id),
                    )
                    return cur.rowcount > 0
    except Exception as e:
        logger.exception("delete_word failed: %s", e)
        return False


def update_word_meaning(user_id: int, word_id: int, meaning: str | None) -> bool:
    """Update meaning/translation for a word row."""
    meaning = (meaning or "").strip() or None
    try:
        with get_connection() as conn:
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute(
                    "UPDATE vocabulary SET meaning = ? WHERE id = ? AND user_id = ?",
                    (meaning, word_id, user_id),
                )
                return cur.rowcount > 0
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        "UPDATE vocabulary SET meaning = %s WHERE id = %s AND user_id = %s",
                        (meaning, word_id, user_id),
                    )
                    return cur.rowcount > 0
    except Exception as e:
        logger.exception("update_word_meaning failed: %s", e)
        return False


# ---------------------------------------------------------------------------
# Cached examples for study mode
# ---------------------------------------------------------------------------


def add_examples_batch(user_id: int, word_id: int, examples: list[str], batch_id: str | None = None) -> str | None:
    """
    Insert a batch of cached examples for a word. Returns batch_id on success.
    """
    # Clean and filter empty lines.
    cleaned = [ex.strip() for ex in (examples or []) if ex and ex.strip()]
    if not cleaned:
        return None
    batch_uuid = uuid.UUID(batch_id) if batch_id else uuid.uuid4()
    try:
        with get_connection() as conn:
            if conn is None:
                return None
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                # Store UUID as string in SQLite.
                cur = conn.cursor()
                cur.executemany(
                    """
                    INSERT INTO vocabulary_examples (user_id, word_id, batch_id, example_text, served)
                    VALUES (?, ?, ?, ?, 0)
                    """,
                    [(user_id, word_id, str(batch_uuid), ex) for ex in cleaned],
                )
            else:
                # Store UUID as UUID in PostgreSQL.
                with conn.cursor() as cur:
                    cur.executemany(
                        """
                        INSERT INTO vocabulary_examples (user_id, word_id, batch_id, example_text, served)
                        VALUES (%s, %s, %s, %s, FALSE)
                        """,
                        [(user_id, word_id, batch_uuid, ex) for ex in cleaned],
                    )
        return str(batch_uuid)
    except Exception as e:
        logger.exception("add_examples_batch failed: %s", e)
        return None


def pop_next_example(user_id: int, word_id: int):
    """
    Mark one unserved example as served and return (id, example_text, batch_id).
    """
    try:
        with get_connection() as conn:
            if conn is None:
                return None
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                # SQLite has no SKIP LOCKED and limited UPDATE ... RETURNING support.
                # We do a simple "select then update" inside one transaction.
                cur = conn.cursor()
                cur.execute(
                    """
                    SELECT id, example_text, batch_id
                    FROM vocabulary_examples
                    WHERE user_id = ? AND word_id = ? AND served = 0
                    ORDER BY created_at ASC, id ASC
                    LIMIT 1
                    """,
                    (user_id, word_id),
                )
                row = cur.fetchone()
                if not row:
                    return None
                ex_id = row[0]
                cur.execute(
                    "UPDATE vocabulary_examples SET served = 1 WHERE id = ?",
                    (ex_id,),
                )
                return row
            else:
                # PostgreSQL: do it atomically and safely for concurrent workers.
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        WITH picked AS (
                            SELECT id
                            FROM vocabulary_examples
                            WHERE user_id = %s AND word_id = %s AND served = FALSE
                            ORDER BY created_at ASC, id ASC
                            LIMIT 1
                            FOR UPDATE SKIP LOCKED
                        )
                        UPDATE vocabulary_examples ve
                        SET served = TRUE
                        FROM picked
                        WHERE ve.id = picked.id
                        RETURNING ve.id, ve.example_text, ve.batch_id
                        """,
                        (user_id, word_id),
                    )
                    return cur.fetchone()
    except Exception as e:
        logger.exception("pop_next_example failed: %s", e)
        return None


def count_unserved_examples(user_id: int, word_id: int) -> int:
    """How many cached examples remain."""
    try:
        with get_connection() as conn:
            if conn is None:
                return 0
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute(
                    """
                    SELECT COUNT(*)
                    FROM vocabulary_examples
                    WHERE user_id = ? AND word_id = ? AND served = 0
                    """,
                    (user_id, word_id),
                )
                row = cur.fetchone()
                return int(row[0]) if row else 0
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        SELECT COUNT(*)
                        FROM vocabulary_examples
                        WHERE user_id = %s AND word_id = %s AND served = FALSE
                        """,
                        (user_id, word_id),
                    )
                    row = cur.fetchone()
                    return int(row[0]) if row else 0
    except Exception as e:
        logger.exception("count_unserved_examples failed: %s", e)
        return 0


# ---------------------------------------------------------------------------
# UX/product state: onboarding + usage stats
# ---------------------------------------------------------------------------


def is_onboarding_done(user_id: int) -> bool:
    """Return True if user finished onboarding."""
    try:
        with get_connection() as conn:
            if conn is None:
                return False
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute(
                    "INSERT OR IGNORE INTO user_profiles (user_id, onboarding_done) VALUES (?, 0)",
                    (user_id,),
                )
                cur.execute(
                    "SELECT onboarding_done FROM user_profiles WHERE user_id = ?",
                    (user_id,),
                )
                row = cur.fetchone()
                return bool(row[0]) if row else False
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO user_profiles (user_id, onboarding_done)
                        VALUES (%s, 0)
                        ON CONFLICT (user_id) DO NOTHING
                        """,
                        (user_id,),
                    )
                    cur.execute(
                        "SELECT onboarding_done FROM user_profiles WHERE user_id = %s",
                        (user_id,),
                    )
                    row = cur.fetchone()
                    return bool(row[0]) if row else False
    except Exception as e:
        logger.exception("is_onboarding_done failed: %s", e)
        return False


def set_onboarding_done(user_id: int, done: bool = True) -> bool:
    """Mark onboarding as done/undone."""
    try:
        with get_connection() as conn:
            if conn is None:
                return False
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            v = 1 if done else 0
            if is_sqlite:
                cur = conn.cursor()
                cur.execute(
                    "INSERT OR IGNORE INTO user_profiles (user_id, onboarding_done) VALUES (?, 0)",
                    (user_id,),
                )
                cur.execute(
                    "UPDATE user_profiles SET onboarding_done = ? WHERE user_id = ?",
                    (v, user_id),
                )
                return cur.rowcount > 0
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO user_profiles (user_id, onboarding_done)
                        VALUES (%s, 0)
                        ON CONFLICT (user_id) DO NOTHING
                        """,
                        (user_id,),
                    )
                    cur.execute(
                        "UPDATE user_profiles SET onboarding_done = %s WHERE user_id = %s",
                        (v, user_id),
                    )
                    return cur.rowcount > 0
    except Exception as e:
        logger.exception("set_onboarding_done failed: %s", e)
        return False


_USAGE_FIELDS = {
    "words_added",
    "examples_generated",
    "examples_served",
    "speaking_turns",
    "speaking_recaps",
}


def increment_usage(user_id: int, field: str, amount: int = 1) -> bool:
    """Increment a usage counter (safe field names only)."""
    if field not in _USAGE_FIELDS:
        return False
    try:
        with get_connection() as conn:
            if conn is None:
                return False
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            amount = int(amount)
            if amount == 0:
                return True

            if is_sqlite:
                cur = conn.cursor()
                cur.execute("INSERT OR IGNORE INTO usage_stats (user_id) VALUES (?)", (user_id,))
                cur.execute(
                    f"UPDATE usage_stats SET {field} = {field} + ? WHERE user_id = ?",
                    (amount, user_id),
                )
                return cur.rowcount > 0
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        "INSERT INTO usage_stats (user_id) VALUES (%s) ON CONFLICT (user_id) DO NOTHING",
                        (user_id,),
                    )
                    cur.execute(
                        f"UPDATE usage_stats SET {field} = {field} + %s WHERE user_id = %s",
                        (amount, user_id),
                    )
                    return cur.rowcount > 0
    except Exception as e:
        logger.exception("increment_usage failed: %s", e)
        return False


def get_usage_stats(user_id: int) -> dict:
    """Get usage counters as a dict."""
    try:
        with get_connection() as conn:
            if conn is None:
                return {}
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute("INSERT OR IGNORE INTO usage_stats (user_id) VALUES (?)", (user_id,))
                cur.execute(
                    """
                    SELECT words_added, examples_generated, examples_served,
                           speaking_turns, speaking_recaps
                    FROM usage_stats WHERE user_id = ?
                    """,
                    (user_id,),
                )
                row = cur.fetchone()
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        "INSERT INTO usage_stats (user_id) VALUES (%s) ON CONFLICT (user_id) DO NOTHING",
                        (user_id,),
                    )
                    cur.execute(
                        """
                        SELECT words_added, examples_generated, examples_served,
                               speaking_turns, speaking_recaps
                        FROM usage_stats WHERE user_id = %s
                        """,
                        (user_id,),
                    )
                    row = cur.fetchone()
            if not row:
                return {}
            return {
                "words_added": int(row[0]),
                "examples_generated": int(row[1]),
                "examples_served": int(row[2]),
                "speaking_turns": int(row[3]),
                "speaking_recaps": int(row[4]),
            }
    except Exception as e:
        logger.exception("get_usage_stats failed: %s", e)
        return {}


# ---------------------------------------------------------------------------
# Persistent Speaking session (survives bot restarts)
# ---------------------------------------------------------------------------


def get_speaking_session(user_id: int):
    """
    Load persisted speaking session.
    Returns dict: {speed: str, conversation_history: list[{"role","content"}]}
    or None if no session.
    """
    try:
        with get_connection() as conn:
            if conn is None:
                return None
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute(
                    "SELECT speed, history_json FROM speaking_sessions WHERE user_id = ?",
                    (user_id,),
                )
                row = cur.fetchone()
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        "SELECT speed, history_json FROM speaking_sessions WHERE user_id = %s",
                        (user_id,),
                    )
                    row = cur.fetchone()
            if not row:
                return None
            speed = row[0] or "normal"
            history_json = row[1] or "[]"
            try:
                history = json.loads(history_json)
            except Exception:
                history = []
            return {"speed": speed, "conversation_history": history}
    except Exception as e:
        logger.exception("get_speaking_session failed: %s", e)
        return None


def set_speaking_session(user_id: int, speed: str, conversation_history: list):
    """Persist current speaking session to DB."""
    try:
        speed = (speed or "normal").strip()
        history_json = json.dumps(conversation_history or [])
        with get_connection() as conn:
            if conn is None:
                return False
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute(
                    """
                    INSERT INTO speaking_sessions (user_id, speed, history_json)
                    VALUES (?, ?, ?)
                    ON CONFLICT(user_id) DO UPDATE SET
                      speed = excluded.speed,
                      history_json = excluded.history_json,
                      updated_at = datetime('now')
                    """,
                    (user_id, speed, history_json),
                )
                return True
            else:
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO speaking_sessions (user_id, speed, history_json)
                        VALUES (%s, %s, %s)
                        ON CONFLICT(user_id) DO UPDATE SET
                          speed = EXCLUDED.speed,
                          history_json = EXCLUDED.history_json,
                          updated_at = NOW()
                        """,
                        (user_id, speed, history_json),
                    )
                    return True
    except Exception as e:
        logger.exception("set_speaking_session failed: %s", e)
        return False


def clear_speaking_session(user_id: int) -> bool:
    """Delete persisted speaking session."""
    try:
        with get_connection() as conn:
            if conn is None:
                return False
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute("DELETE FROM speaking_sessions WHERE user_id = ?", (user_id,))
                return cur.rowcount > 0
            else:
                with conn.cursor() as cur:
                    cur.execute("DELETE FROM speaking_sessions WHERE user_id = %s", (user_id,))
                    return cur.rowcount > 0
    except Exception as e:
        logger.exception("clear_speaking_session failed: %s", e)
        return False


# ---------------------------------------------------------------------------
# Persistent Vocabulary study state (helps after bot restart)
# ---------------------------------------------------------------------------


def set_vocab_active_word(user_id: int, word_id: int | None) -> bool:
    """
    Store which word is currently opened in "study" mode for the user.
    Used only as a UX improvement after restarts.
    """
    try:
        with get_connection() as conn:
            if conn is None:
                return False
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                if word_id is None:
                    cur.execute("UPDATE vocab_active_session SET word_id = NULL WHERE user_id = ?", (user_id,))
                    if cur.rowcount == 0:
                        cur.execute("INSERT OR IGNORE INTO vocab_active_session (user_id, word_id) VALUES (?, NULL)", (user_id,))
                else:
                    cur.execute(
                        """
                        INSERT INTO vocab_active_session (user_id, word_id)
                        VALUES (?, ?)
                        ON CONFLICT(user_id) DO UPDATE SET word_id = excluded.word_id, updated_at = datetime('now')
                        """,
                        (user_id, int(word_id)),
                    )
                return True
            else:
                with conn.cursor() as cur:
                    if word_id is None:
                        cur.execute("UPDATE vocab_active_session SET word_id = NULL WHERE user_id = %s", (user_id,))
                        return True
                    cur.execute(
                        """
                        INSERT INTO vocab_active_session (user_id, word_id)
                        VALUES (%s, %s)
                        ON CONFLICT(user_id) DO UPDATE SET
                          word_id = EXCLUDED.word_id,
                          updated_at = NOW()
                        """,
                        (user_id, int(word_id)),
                    )
                    return True
    except Exception as e:
        logger.exception("set_vocab_active_word failed: %s", e)
        return False


def get_vocab_active_word(user_id: int) -> int | None:
    """Return active word_id for user or None."""
    try:
        with get_connection() as conn:
            if conn is None:
                return None
            is_sqlite = conn.__class__.__module__.startswith("sqlite3")
            if is_sqlite:
                cur = conn.cursor()
                cur.execute("SELECT word_id FROM vocab_active_session WHERE user_id = ?", (user_id,))
                row = cur.fetchone()
            else:
                with conn.cursor() as cur:
                    cur.execute("SELECT word_id FROM vocab_active_session WHERE user_id = %s", (user_id,))
                    row = cur.fetchone()
            if not row:
                return None
            return int(row[0]) if row[0] is not None else None
    except Exception as e:
        logger.exception("get_vocab_active_word failed: %s", e)
        return None


def clear_vocab_active_word(user_id: int) -> bool:
    """Clear active word for the user."""
    return set_vocab_active_word(user_id, None)
